/**
 * Service to manage application data natively inside Shopify using Metaobjects and Metafields.
 * This completely replaces the need for an external Prisma-managed database.
 */
import db from "../db.server";

// A simple utility to parse JSON safely
function parseJson(str, fallback = {}) {
  try {
    return str ? JSON.parse(str) : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Maps a Shopify Metaobject record back to the Prisma-like image generation structure.
 */
export function mapMetaobjectToGeneration(metaobject) {
  if (!metaobject) return null;

  const fields = {};
  if (Array.isArray(metaobject.fields)) {
    for (const field of metaobject.fields) {
      fields[field.key] = field.value;
    }
  }

  // Virtualize the customer object to match Prisma includes
  const customer = fields.customer_id
    ? {
        id: fields.customer_id,
        shopifyCustomerId: fields.customer_id,
        email: fields.customer_email || null,
        displayName: fields.customer_email
          ? fields.customer_email.split("@")[0]
          : "Customer",
      }
    : null;

  return {
    id: metaobject.id,
    handle: metaobject.handle,
    prompt: fields.prompt || "",
    status: fields.status || "PENDING",
    visibility: fields.visibility || "PRIVATE",
    moderationStatus: fields.moderation_status || "PENDING",
    imageUrl: fields.image_url || null,
    productId: fields.product_id || null,
    productHandle: fields.product_handle || null,
    variantId: fields.variant_id || null,
    variantTitle: fields.variant_title || null,
    shopifyMediaId: fields.shopify_media_id || null,
    moderationReason: fields.moderation_reason || null,
    watermarkText: fields.watermark_text || "Generated by AI",
    openAiRequestId: fields.openai_request_id || null,
    errorMessage: fields.error_message || null,
    metadata: fields.metadata || "{}",
    customerId: fields.customer_id || null,
    customerEmail: fields.customer_email || null,
    createdAt: fields.created_at || new Date().toISOString(),
    updatedAt: fields.created_at || new Date().toISOString(),
    customer,
  };
}

function mapDatabaseGenerationToGeneration(generation) {
  if (!generation) return null;

  const customer = generation.customer
    ? {
        id: generation.customer.id,
        shopifyCustomerId: generation.customer.shopifyCustomerId,
        email: generation.customer.email || null,
        displayName:
          generation.customer.displayName ||
          generation.customer.email?.split("@")[0] ||
          "Customer",
      }
    : null;

  return {
    id: generation.id,
    handle: generation.id,
    prompt: generation.prompt || "",
    status: generation.status || "PENDING",
    visibility: generation.visibility || "PRIVATE",
    moderationStatus: generation.moderationStatus || "PENDING",
    imageUrl: generation.imageUrl || null,
    productId: generation.productId || null,
    productHandle: generation.productHandle || null,
    variantId: generation.variantId || null,
    variantTitle: generation.variantTitle || null,
    shopifyMediaId: generation.shopifyMediaId || null,
    moderationReason: generation.moderationReason || null,
    watermarkText: generation.watermarkText || "Generated by AI",
    openAiRequestId: generation.openAiRequestId || null,
    errorMessage: generation.errorMessage || null,
    metadata: generation.metadata || "{}",
    customerId: customer?.shopifyCustomerId || generation.customerId || null,
    customerEmail: customer?.email || null,
    selectedForCart: generation.selectedForCart || false,
    createdAt:
      generation.createdAt instanceof Date
        ? generation.createdAt.toISOString()
        : generation.createdAt,
    updatedAt:
      generation.updatedAt instanceof Date
        ? generation.updatedAt.toISOString()
        : generation.updatedAt,
    customer,
  };
}

async function ensureDatabaseShop(shopDomain) {
  if (!shopDomain) {
    throw new Error("shopId is required to save image generations.");
  }

  return db.shop.upsert({
    where: { shop: shopDomain },
    update: {},
    create: {
      shop: shopDomain,
      settings: "{}",
    },
  });
}

async function ensureDatabaseCustomer({ shopId, shopifyCustomerId, email }) {
  if (!shopifyCustomerId) return null;

  const existing = await db.customerAccount.findFirst({
    where: {
      shopId,
      shopifyCustomerId,
    },
  });

  if (existing) {
    return db.customerAccount.update({
      where: { id: existing.id },
      data: {
        email: email || existing.email,
        displayName: email?.split("@")[0] || existing.displayName || "Customer",
      },
    });
  }

  return db.customerAccount.create({
    data: {
      shopId,
      shopifyCustomerId,
      email: email || null,
      displayName: email ? email.split("@")[0] : "Customer",
    },
  });
}

function assertPublicImageUrl(imageUrl) {
  if (!imageUrl) return;
  if (String(imageUrl).startsWith("data:") || String(imageUrl).length > 2048) {
    throw new Error(
      "Generated image must be uploaded to a public URL before it is saved.",
    );
  }
}

function safeDbString(value, maxLength = 180) {
  if (value === undefined || value === null) return null;
  const stringValue = typeof value === "string" ? value : JSON.stringify(value);
  return stringValue.length > maxLength
    ? stringValue.slice(0, maxLength)
    : stringValue;
}

function customerIdVariants(customerId) {
  if (!customerId) return [];

  const raw = String(customerId);
  const numeric = raw.match(/Customer\/([^/]+)$/)?.[1] || raw;
  return Array.from(
    new Set([raw, numeric, `gid://shopify/Customer/${numeric}`]),
  );
}

/**
 * Verifies that the `ai_image_generation` Metaobject definition exists.
 * If it doesn't, automatically creates it in the merchant's store.
 */
export async function ensureMetaobjectDefinition(admin) {
  try {
    // 1. Check if definition already exists
    const checkQuery = `#graphql
      query GetMetaobjectDefinition {
        metaobjectDefinitionByType(type: "ai_image_generation") {
          id
          type
          name
        }
      }
    `;

    const checkResponse = await admin.graphql(checkQuery);
    const checkResult = await checkResponse.json();

    if (checkResult.data?.metaobjectDefinitionByType) {
      return checkResult.data.metaobjectDefinitionByType;
    }

    // 2. Define the schema if it doesn't exist
    const createMutation = `#graphql
      mutation CreateMetaobjectDefinition($definition: MetaobjectDefinitionCreateInput!) {
        metaobjectDefinitionCreate(definition: $definition) {
          metaobjectDefinition {
            id
            type
          }
          userErrors {
            field
            message
          }
        }
      }
    `;

    const variables = {
      definition: {
        name: "AI Image Generation",
        type: "ai_image_generation",
        fieldDefinitions: [
          { name: "Prompt", key: "prompt", type: "multi_line_text_field" },
          { name: "Status", key: "status", type: "single_line_text_field" },
          {
            name: "Visibility",
            key: "visibility",
            type: "single_line_text_field",
          },
          {
            name: "Moderation Status",
            key: "moderation_status",
            type: "single_line_text_field",
          },
          {
            name: "Image URL",
            key: "image_url",
            type: "single_line_text_field",
          },
          {
            name: "Product ID",
            key: "product_id",
            type: "single_line_text_field",
          },
          {
            name: "Product Handle",
            key: "product_handle",
            type: "single_line_text_field",
          },
          {
            name: "Variant ID",
            key: "variant_id",
            type: "single_line_text_field",
          },
          {
            name: "Variant Title",
            key: "variant_title",
            type: "single_line_text_field",
          },
          {
            name: "Shopify Media ID",
            key: "shopify_media_id",
            type: "single_line_text_field",
          },
          {
            name: "Moderation Reason",
            key: "moderation_reason",
            type: "single_line_text_field",
          },
          {
            name: "Watermark Text",
            key: "watermark_text",
            type: "single_line_text_field",
          },
          {
            name: "OpenAI Request ID",
            key: "openai_request_id",
            type: "single_line_text_field",
          },
          {
            name: "Error Message",
            key: "error_message",
            type: "single_line_text_field",
          },
          { name: "Metadata", key: "metadata", type: "json" },
          {
            name: "Customer ID",
            key: "customer_id",
            type: "single_line_text_field",
          },
          {
            name: "Customer Email",
            key: "customer_email",
            type: "single_line_text_field",
          },
          {
            name: "Created At",
            key: "created_at",
            type: "single_line_text_field",
          },
        ],
      },
    };

    const createResponse = await admin.graphql(createMutation, { variables });
    const createResult = await createResponse.json();

    const errors =
      createResult.data?.metaobjectDefinitionCreate?.userErrors || [];
    if (errors.length) {
      console.error("Failed to create metaobject definition:", errors);
      throw new Error(errors.map((e) => e.message).join(", "));
    }

    return createResult.data?.metaobjectDefinitionCreate?.metaobjectDefinition;
  } catch (err) {
    console.error("ensureMetaobjectDefinition error", err);
    return null;
  }
}

/**
 * Gets Shop customization settings from standard Shop Metafields.
 */
export async function getShopSettings(admin) {
  const query = `#graphql
    query GetShopSettings {
      shop {
        id
        metafield(namespace: "ai_image_manager", key: "settings") {
          value
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query);
    const result = await response.json();
    return result.data?.shop?.metafield?.value || null;
  } catch (err) {
    console.error("getShopSettings error", err);
    return null;
  }
}

/**
 * Updates Shop customization settings in standard Shop Metafields.
 */
export async function updateShopSettings(admin, settingsStr) {
  // First, we need to query the shop ID to set the ownerId
  const shopIdQuery = `#graphql
    query GetShopId {
      shop {
        id
      }
    }
  `;

  try {
    const shopIdRes = await admin.graphql(shopIdQuery);
    const shopIdJson = await shopIdRes.json();
    const shopId = shopIdJson.data?.shop?.id;

    if (!shopId) throw new Error("Could not fetch shop ID");

    const mutation = `#graphql
      mutation SetShopSettings($metafields: [MetafieldsSetInput!]!) {
        metafieldsSet(metafields: $metafields) {
          metafields {
            id
            value
          }
          userErrors {
            field
            message
          }
        }
      }
    `;

    const variables = {
      metafields: [
        {
          ownerId: shopId,
          namespace: "ai_image_manager",
          key: "settings",
          type: "json",
          value: settingsStr,
        },
      ],
    };

    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metafieldsSet?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map((e) => e.message).join(", "));
    }

    return result.data?.metafieldsSet?.metafields?.[0];
  } catch (err) {
    console.error("updateShopSettings error", err);
    throw err;
  }
}

/**
 * Gets a Customer approval profile metafield.
 */
export async function getCustomerProfile(admin, customerId) {
  if (!customerId) return null;

  // Normalize ID (needs to have gid://shopify/Customer/ prefix)
  const fullCustomerId = customerId.startsWith("gid://shopify/")
    ? customerId
    : `gid://shopify/Customer/${customerId}`;

  const query = `#graphql
    query GetCustomerProfile($id: ID!) {
      customer(id: $id) {
        id
        metafield(namespace: "ai_image_manager", key: "profile") {
          value
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query, {
      variables: { id: fullCustomerId },
    });
    const result = await response.json();
    const rawVal = result.data?.customer?.metafield?.value;
    return rawVal ? parseJson(rawVal) : null;
  } catch (err) {
    console.error("getCustomerProfile error", err);
    return null;
  }
}

/**
 * Updates a Customer approval profile metafield.
 */
export async function updateCustomerProfile(admin, customerId, profileData) {
  if (!customerId) return null;

  const fullCustomerId = customerId.startsWith("gid://shopify/")
    ? customerId
    : `gid://shopify/Customer/${customerId}`;

  // Fetch existing profile to merge updates
  const existing = (await getCustomerProfile(admin, fullCustomerId)) || {};
  const nextProfile = {
    isApproved: true,
    generationLimit: null,
    totalGenerations: 0,
    ...existing,
    ...profileData,
  };

  const mutation = `#graphql
    mutation SetCustomerProfile($metafields: [MetafieldsSetInput!]!) {
      metafieldsSet(metafields: $metafields) {
        metafields {
          id
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  const variables = {
    metafields: [
      {
        ownerId: fullCustomerId,
        namespace: "ai_image_manager",
        key: "profile",
        type: "json",
        value: JSON.stringify(nextProfile),
      },
    ],
  };

  try {
    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metafieldsSet?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map((e) => e.message).join(", "));
    }
    return nextProfile;
  } catch (err) {
    console.error("updateCustomerProfile error", err);
    throw err;
  }
}

/**
 * Creates an `ai_image_generation` Metaobject.
 */
export async function createAiImageGeneration(admin, data) {
  try {
    assertPublicImageUrl(data.imageUrl);
    const shop = await ensureDatabaseShop(data.shopId);
    const customer = await ensureDatabaseCustomer({
      shopId: shop.id,
      shopifyCustomerId: data.customerId,
      email: data.customerEmail,
    });

    const generation = await db.aiImageGeneration.create({
      data: {
        shopId: shop.id,
        customerId: customer?.id || null,
        productId: safeDbString(data.productId),
        productHandle: safeDbString(data.productHandle),
        variantId: safeDbString(data.variantId),
        variantTitle: safeDbString(data.variantTitle),
        prompt: safeDbString(data.prompt) || "",
        imageUrl: data.imageUrl || null,
        shopifyMediaId: safeDbString(data.shopifyMediaId),
        status: data.status || "PENDING",
        visibility: data.visibility || "PRIVATE",
        moderationStatus: data.moderationStatus || "PENDING",
        moderationReason: safeDbString(data.moderationReason),
        watermarkText: safeDbString(data.watermarkText) || "Generated by AI",
        openAiRequestId: safeDbString(data.openAiRequestId),
        errorMessage: safeDbString(data.errorMessage),
        metadata: safeDbString(data.metadata) || "{}",
        selectedForCart: Boolean(data.selectedForCart),
      },
      include: { customer: true },
    });

    return mapDatabaseGenerationToGeneration(generation);
  } catch (err) {
    console.error("createAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Updates an `ai_image_generation` Metaobject.
 */
export async function updateAiImageGeneration(admin, id, data) {
  try {
    assertPublicImageUrl(data.imageUrl);
    const updateData = {};

    if (data.prompt !== undefined)
      updateData.prompt = safeDbString(data.prompt);
    if (data.status !== undefined) updateData.status = data.status;
    if (data.visibility !== undefined) updateData.visibility = data.visibility;
    if (data.moderationStatus !== undefined) {
      updateData.moderationStatus = data.moderationStatus;
    }
    if (data.imageUrl !== undefined)
      updateData.imageUrl = data.imageUrl || null;
    if (data.productId !== undefined)
      updateData.productId = safeDbString(data.productId);
    if (data.productHandle !== undefined) {
      updateData.productHandle = safeDbString(data.productHandle);
    }
    if (data.variantId !== undefined)
      updateData.variantId = safeDbString(data.variantId);
    if (data.variantTitle !== undefined) {
      updateData.variantTitle = safeDbString(data.variantTitle);
    }
    if (data.shopifyMediaId !== undefined) {
      updateData.shopifyMediaId = safeDbString(data.shopifyMediaId);
    }
    if (data.moderationReason !== undefined) {
      updateData.moderationReason = safeDbString(data.moderationReason);
    }
    if (data.watermarkText !== undefined) {
      updateData.watermarkText =
        safeDbString(data.watermarkText) || "Generated by AI";
    }
    if (data.openAiRequestId !== undefined) {
      updateData.openAiRequestId = safeDbString(data.openAiRequestId);
    }
    if (data.errorMessage !== undefined) {
      updateData.errorMessage = safeDbString(data.errorMessage);
    }
    if (data.metadata !== undefined)
      updateData.metadata = safeDbString(data.metadata) || "{}";
    if (data.selectedForCart !== undefined) {
      updateData.selectedForCart = Boolean(data.selectedForCart);
    }

    const generation = await db.aiImageGeneration.update({
      where: { id },
      data: updateData,
      include: { customer: true },
    });

    return mapDatabaseGenerationToGeneration(generation);
  } catch (err) {
    console.error("updateAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Deletes an `ai_image_generation` Metaobject.
 */
export async function deleteAiImageGeneration(admin, id) {
  try {
    await db.aiImageGeneration.delete({ where: { id } });
    return id;
  } catch (err) {
    console.error("deleteAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Fetch a single AI Image Generation by ID.
 */
export async function getAiImageGeneration(admin, id) {
  try {
    const generation = await db.aiImageGeneration.findUnique({
      where: { id },
      include: { customer: true },
    });
    return mapDatabaseGenerationToGeneration(generation);
  } catch (err) {
    console.error("getAiImageGeneration error", err);
    return null;
  }
}

/**
 * Queries AI Image Generations from Shopify Metaobjects.
 * Supports standard filters.
 */
export async function getAiImageGenerations(admin, filter = {}) {
  try {
    const where = {};
    let dbShopId = null;
    if (filter.shopId) {
      const shop = await db.shop.findUnique({ where: { shop: filter.shopId } });
      dbShopId = shop?.id || "__missing_shop__";
      where.shopId = dbShopId;
    }
    if (filter.customerId) {
      if (dbShopId) {
        const customer = await db.customerAccount.findFirst({
          where: {
            shopId: dbShopId,
            shopifyCustomerId: {
              in: customerIdVariants(filter.customerId),
            },
          },
        });
        where.customerId = customer?.id || "__missing_customer__";
      } else {
        where.customerId = filter.customerId;
      }
    }
    if (filter.productId) where.productId = filter.productId;
    if (filter.visibility) where.visibility = filter.visibility;
    if (filter.moderationStatus) {
      where.moderationStatus = filter.moderationStatus;
    }
    if (filter.status) where.status = filter.status;

    const generations = await db.aiImageGeneration.findMany({
      where,
      include: { customer: true },
      orderBy: { createdAt: "desc" },
      take: filter.take || 100,
    });

    let list = generations.map(mapDatabaseGenerationToGeneration);
    if (filter.customerEmail) {
      list = list.filter((item) => item.customerEmail === filter.customerEmail);
    }
    return list;
  } catch (err) {
    console.error("getAiImageGenerations error", err);
    return [];
  }
}

/**
 * Queries list of Shopify customers along with their `ai_image_manager.profile` metafields.
 */
export async function getCustomers(admin) {
  const query = `#graphql
    query GetCustomers {
      customers(first: 100) {
        edges {
          node {
            id
            displayName
            email
            metafield(namespace: "ai_image_manager", key: "profile") {
              value
            }
          }
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query);
    const result = await response.json();
    const edges = result.data?.customers?.edges || [];

    const generations = await getAiImageGenerations(admin);

    return edges.map(({ node }) => {
      const profile = node.metafield?.value
        ? parseJson(node.metafield.value)
        : {};

      // Calculate active generation count for this specific customer
      const customerIds = customerIdVariants(node.id);
      const count = generations.filter(
        (gen) =>
          customerIds.includes(gen.customerId) ||
          customerIds.includes(gen.customer?.shopifyCustomerId),
      ).length;

      return {
        id: node.id,
        shopifyCustomerId: node.id,
        displayName: node.displayName || node.email || "Shopify Customer",
        email: node.email,
        isApproved: profile.isApproved !== false, // default true
        generationLimit: profile.generationLimit ?? null,
        _count: {
          generations: count,
        },
      };
    });
  } catch (err) {
    console.error("getCustomers error", err);
    return [];
  }
}
