/**
 * Service to manage application data natively inside Shopify using Metaobjects and Metafields.
 * This completely replaces the need for an external Prisma-managed database.
 */

// A simple utility to parse JSON safely
function parseJson(str, fallback = {}) {
  try {
    return str ? JSON.parse(str) : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Maps a Shopify Metaobject record back to the Prisma-like image generation structure.
 */
export function mapMetaobjectToGeneration(metaobject) {
  if (!metaobject) return null;

  const fields = {};
  if (Array.isArray(metaobject.fields)) {
    for (const field of metaobject.fields) {
      fields[field.key] = field.value;
    }
  }

  // Virtualize the customer object to match Prisma includes
  const customer = fields.customer_id ? {
    id: fields.customer_id,
    shopifyCustomerId: fields.customer_id,
    email: fields.customer_email || null,
    displayName: fields.customer_email ? fields.customer_email.split("@")[0] : "Customer",
  } : null;

  return {
    id: metaobject.id,
    handle: metaobject.handle,
    prompt: fields.prompt || "",
    status: fields.status || "PENDING",
    visibility: fields.visibility || "PRIVATE",
    moderationStatus: fields.moderation_status || "PENDING",
    imageUrl: fields.image_url || null,
    productId: fields.product_id || null,
    productHandle: fields.product_handle || null,
    variantId: fields.variant_id || null,
    variantTitle: fields.variant_title || null,
    shopifyMediaId: fields.shopify_media_id || null,
    moderationReason: fields.moderation_reason || null,
    watermarkText: fields.watermark_text || "Generated by AI",
    openAiRequestId: fields.openai_request_id || null,
    errorMessage: fields.error_message || null,
    metadata: fields.metadata || "{}",
    customerId: fields.customer_id || null,
    customerEmail: fields.customer_email || null,
    createdAt: fields.created_at || new Date().toISOString(),
    updatedAt: fields.created_at || new Date().toISOString(),
    customer,
  };
}

/**
 * Verifies that the `ai_image_generation` Metaobject definition exists.
 * If it doesn't, automatically creates it in the merchant's store.
 */
export async function ensureMetaobjectDefinition(admin) {
  try {
    // 1. Check if definition already exists
    const checkQuery = `#graphql
      query GetMetaobjectDefinition {
        metaobjectDefinitionByType(type: "ai_image_generation") {
          id
          type
          name
        }
      }
    `;

    const checkResponse = await admin.graphql(checkQuery);
    const checkResult = await checkResponse.json();

    if (checkResult.data?.metaobjectDefinitionByType) {
      return checkResult.data.metaobjectDefinitionByType;
    }

    // 2. Define the schema if it doesn't exist
    const createMutation = `#graphql
      mutation CreateMetaobjectDefinition($definition: MetaobjectDefinitionCreateInput!) {
        metaobjectDefinitionCreate(definition: $definition) {
          metaobjectDefinition {
            id
            type
          }
          userErrors {
            field
            message
          }
        }
      }
    `;

    const variables = {
      definition: {
        name: "AI Image Generation",
        type: "ai_image_generation",
        fieldDefinitions: [
          { name: "Prompt", key: "prompt", type: "multi_line_text_field" },
          { name: "Status", key: "status", type: "single_line_text_field" },
          { name: "Visibility", key: "visibility", type: "single_line_text_field" },
          { name: "Moderation Status", key: "moderation_status", type: "single_line_text_field" },
          { name: "Image URL", key: "image_url", type: "single_line_text_field" },
          { name: "Product ID", key: "product_id", type: "single_line_text_field" },
          { name: "Product Handle", key: "product_handle", type: "single_line_text_field" },
          { name: "Variant ID", key: "variant_id", type: "single_line_text_field" },
          { name: "Variant Title", key: "variant_title", type: "single_line_text_field" },
          { name: "Shopify Media ID", key: "shopify_media_id", type: "single_line_text_field" },
          { name: "Moderation Reason", key: "moderation_reason", type: "single_line_text_field" },
          { name: "Watermark Text", key: "watermark_text", type: "single_line_text_field" },
          { name: "OpenAI Request ID", key: "openai_request_id", type: "single_line_text_field" },
          { name: "Error Message", key: "error_message", type: "single_line_text_field" },
          { name: "Metadata", key: "metadata", type: "json" },
          { name: "Customer ID", key: "customer_id", type: "single_line_text_field" },
          { name: "Customer Email", key: "customer_email", type: "single_line_text_field" },
          { name: "Created At", key: "created_at", type: "single_line_text_field" }
        ]
      }
    };

    const createResponse = await admin.graphql(createMutation, { variables });
    const createResult = await createResponse.json();

    const errors = createResult.data?.metaobjectDefinitionCreate?.userErrors || [];
    if (errors.length) {
      console.error("Failed to create metaobject definition:", errors);
      throw new Error(errors.map(e => e.message).join(", "));
    }

    return createResult.data?.metaobjectDefinitionCreate?.metaobjectDefinition;
  } catch (err) {
    console.error("ensureMetaobjectDefinition error", err);
    return null;
  }
}

/**
 * Gets Shop customization settings from standard Shop Metafields.
 */
export async function getShopSettings(admin) {
  const query = `#graphql
    query GetShopSettings {
      shop {
        id
        metafield(namespace: "ai_image_manager", key: "settings") {
          value
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query);
    const result = await response.json();
    return result.data?.shop?.metafield?.value || null;
  } catch (err) {
    console.error("getShopSettings error", err);
    return null;
  }
}

/**
 * Updates Shop customization settings in standard Shop Metafields.
 */
export async function updateShopSettings(admin, settingsStr) {
  // First, we need to query the shop ID to set the ownerId
  const shopIdQuery = `#graphql
    query GetShopId {
      shop {
        id
      }
    }
  `;

  try {
    const shopIdRes = await admin.graphql(shopIdQuery);
    const shopIdJson = await shopIdRes.json();
    const shopId = shopIdJson.data?.shop?.id;

    if (!shopId) throw new Error("Could not fetch shop ID");

    const mutation = `#graphql
      mutation SetShopSettings($metafields: [MetafieldsSetInput!]!) {
        metafieldsSet(metafields: $metafields) {
          metafields {
            id
            value
          }
          userErrors {
            field
            message
          }
        }
      }
    `;

    const variables = {
      metafields: [
        {
          ownerId: shopId,
          namespace: "ai_image_manager",
          key: "settings",
          type: "json",
          value: settingsStr,
        }
      ]
    };

    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metafieldsSet?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map(e => e.message).join(", "));
    }

    return result.data?.metafieldsSet?.metafields?.[0];
  } catch (err) {
    console.error("updateShopSettings error", err);
    throw err;
  }
}

/**
 * Gets a Customer approval profile metafield.
 */
export async function getCustomerProfile(admin, customerId) {
  if (!customerId) return null;

  // Normalize ID (needs to have gid://shopify/Customer/ prefix)
  const fullCustomerId = customerId.startsWith("gid://shopify/")
    ? customerId
    : `gid://shopify/Customer/${customerId}`;

  const query = `#graphql
    query GetCustomerProfile($id: ID!) {
      customer(id: $id) {
        id
        metafield(namespace: "ai_image_manager", key: "profile") {
          value
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query, { variables: { id: fullCustomerId } });
    const result = await response.json();
    const rawVal = result.data?.customer?.metafield?.value;
    return rawVal ? parseJson(rawVal) : null;
  } catch (err) {
    console.error("getCustomerProfile error", err);
    return null;
  }
}

/**
 * Updates a Customer approval profile metafield.
 */
export async function updateCustomerProfile(admin, customerId, profileData) {
  if (!customerId) return null;

  const fullCustomerId = customerId.startsWith("gid://shopify/")
    ? customerId
    : `gid://shopify/Customer/${customerId}`;

  // Fetch existing profile to merge updates
  const existing = await getCustomerProfile(admin, fullCustomerId) || {};
  const nextProfile = {
    isApproved: true,
    generationLimit: null,
    totalGenerations: 0,
    ...existing,
    ...profileData,
  };

  const mutation = `#graphql
    mutation SetCustomerProfile($metafields: [MetafieldsSetInput!]!) {
      metafieldsSet(metafields: $metafields) {
        metafields {
          id
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  const variables = {
    metafields: [
      {
        ownerId: fullCustomerId,
        namespace: "ai_image_manager",
        key: "profile",
        type: "json",
        value: JSON.stringify(nextProfile),
      }
    ]
  };

  try {
    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metafieldsSet?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map(e => e.message).join(", "));
    }
    return nextProfile;
  } catch (err) {
    console.error("updateCustomerProfile error", err);
    throw err;
  }
}

/**
 * Creates an `ai_image_generation` Metaobject.
 */
export async function createAiImageGeneration(admin, data) {
  await ensureMetaobjectDefinition(admin);

  const mutation = `#graphql
    mutation CreateMetaobject($metaobject: MetaobjectCreateInput!) {
      metaobjectCreate(metaobject: $metaobject) {
        metaobject {
          id
          handle
          fields {
            key
            value
          }
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  // Construct fields payload
  const fields = [
    { key: "prompt", value: data.prompt || "" },
    { key: "status", value: data.status || "PENDING" },
    { key: "visibility", value: data.visibility || "PRIVATE" },
    { key: "moderation_status", value: data.moderationStatus || "PENDING" },
    { key: "image_url", value: data.imageUrl || "" },
    { key: "product_id", value: data.productId || "" },
    { key: "product_handle", value: data.productHandle || "" },
    { key: "variant_id", value: data.variantId || "" },
    { key: "variant_title", value: data.variantTitle || "" },
    { key: "shopify_media_id", value: data.shopifyMediaId || "" },
    { key: "moderation_reason", value: data.moderationReason || "" },
    { key: "watermark_text", value: data.watermarkText || "Generated by AI" },
    { key: "openai_request_id", value: data.openAiRequestId || "" },
    { key: "error_message", value: data.errorMessage || "" },
    { key: "metadata", value: data.metadata || "{}" },
    { key: "customer_id", value: data.customerId || "" },
    { key: "customer_email", value: data.customerEmail || "" },
    { key: "created_at", value: data.createdAt || new Date().toISOString() },
  ];

  const variables = {
    metaobject: {
      type: "ai_image_generation",
      fields,
    }
  };

  try {
    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metaobjectCreate?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map(e => e.message).join(", "));
    }

    return mapMetaobjectToGeneration(result.data?.metaobjectCreate?.metaobject);
  } catch (err) {
    console.error("createAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Updates an `ai_image_generation` Metaobject.
 */
export async function updateAiImageGeneration(admin, id, data) {
  const mutation = `#graphql
    mutation UpdateMetaobject($id: ID!, $metaobject: MetaobjectUpdateInput!) {
      metaobjectUpdate(id: $id, metaobject: $metaobject) {
        metaobject {
          id
          handle
          fields {
            key
            value
          }
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  // Map to Shopify field keys
  const fields = [];
  if (data.prompt !== undefined) fields.push({ key: "prompt", value: data.prompt });
  if (data.status !== undefined) fields.push({ key: "status", value: data.status });
  if (data.visibility !== undefined) fields.push({ key: "visibility", value: data.visibility });
  if (data.moderationStatus !== undefined) fields.push({ key: "moderation_status", value: data.moderationStatus });
  if (data.imageUrl !== undefined) fields.push({ key: "image_url", value: data.imageUrl || "" });
  if (data.productId !== undefined) fields.push({ key: "product_id", value: data.productId || "" });
  if (data.productHandle !== undefined) fields.push({ key: "product_handle", value: data.productHandle || "" });
  if (data.variantId !== undefined) fields.push({ key: "variant_id", value: data.variantId || "" });
  if (data.variantTitle !== undefined) fields.push({ key: "variant_title", value: data.variantTitle || "" });
  if (data.shopifyMediaId !== undefined) fields.push({ key: "shopify_media_id", value: data.shopifyMediaId || "" });
  if (data.moderationReason !== undefined) fields.push({ key: "moderation_reason", value: data.moderationReason || "" });
  if (data.watermarkText !== undefined) fields.push({ key: "watermark_text", value: data.watermarkText || "" });
  if (data.openAiRequestId !== undefined) fields.push({ key: "openai_request_id", value: data.openAiRequestId || "" });
  if (data.errorMessage !== undefined) fields.push({ key: "error_message", value: data.errorMessage || "" });
  if (data.metadata !== undefined) fields.push({ key: "metadata", value: data.metadata || "{}" });
  if (data.customerId !== undefined) fields.push({ key: "customer_id", value: data.customerId || "" });
  if (data.customerEmail !== undefined) fields.push({ key: "customer_email", value: data.customerEmail || "" });

  const variables = {
    id,
    metaobject: {
      fields,
    }
  };

  try {
    const response = await admin.graphql(mutation, { variables });
    const result = await response.json();
    const errors = result.data?.metaobjectUpdate?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map(e => e.message).join(", "));
    }

    return mapMetaobjectToGeneration(result.data?.metaobjectUpdate?.metaobject);
  } catch (err) {
    console.error("updateAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Deletes an `ai_image_generation` Metaobject.
 */
export async function deleteAiImageGeneration(admin, id) {
  const mutation = `#graphql
    mutation DeleteMetaobject($id: ID!) {
      metaobjectDelete(id: $id) {
        deletedId
        userErrors {
          field
          message
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(mutation, { variables: { id } });
    const result = await response.json();
    const errors = result.data?.metaobjectDelete?.userErrors || [];
    if (errors.length) {
      throw new Error(errors.map(e => e.message).join(", "));
    }
    return result.data?.metaobjectDelete?.deletedId;
  } catch (err) {
    console.error("deleteAiImageGeneration error", err);
    throw err;
  }
}

/**
 * Fetch a single AI Image Generation by ID.
 */
export async function getAiImageGeneration(admin, id) {
  const query = `#graphql
    query GetMetaobject($id: ID!) {
      metaobject(id: $id) {
        id
        handle
        type
        fields {
          key
          value
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query, { variables: { id } });
    const result = await response.json();
    return mapMetaobjectToGeneration(result.data?.metaobject);
  } catch (err) {
    console.error("getAiImageGeneration error", err);
    return null;
  }
}

/**
 * Queries AI Image Generations from Shopify Metaobjects.
 * Supports standard filters.
 */
export async function getAiImageGenerations(admin, filter = {}) {
  await ensureMetaobjectDefinition(admin);

  const query = `#graphql
    query GetMetaobjects($type: String!, $first: Int!) {
      metaobjects(type: $type, first: $first) {
        edges {
          node {
            id
            handle
            type
            fields {
              key
              value
            }
          }
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query, {
      variables: {
        type: "ai_image_generation",
        first: 100, // Fetch up to 100 generations
      }
    });
    const result = await response.json();
    const edges = result.data?.metaobjects?.edges || [];
    
    // Map Metaobjects and apply in-memory filtering for robustness and simple logic
    let list = edges.map(({ node }) => mapMetaobjectToGeneration(node));

    if (filter.customerId) {
      list = list.filter(item => item.customerId === filter.customerId);
    }
    if (filter.customerEmail) {
      list = list.filter(item => item.customerEmail === filter.customerEmail);
    }
    if (filter.productId) {
      list = list.filter(item => item.productId === filter.productId);
    }
    if (filter.visibility) {
      list = list.filter(item => item.visibility === filter.visibility);
    }
    if (filter.moderationStatus) {
      list = list.filter(item => item.moderationStatus === filter.moderationStatus);
    }
    if (filter.status) {
      list = list.filter(item => item.status === filter.status);
    }

    // Sort by createdAt descending
    list.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

    if (filter.take) {
      list = list.slice(0, filter.take);
    }

    return list;
  } catch (err) {
    console.error("getAiImageGenerations error", err);
    return [];
  }
}

/**
 * Queries list of Shopify customers along with their `ai_image_manager.profile` metafields.
 */
export async function getCustomers(admin) {
  const query = `#graphql
    query GetCustomers {
      customers(first: 100) {
        edges {
          node {
            id
            displayName
            email
            metafield(namespace: "ai_image_manager", key: "profile") {
              value
            }
          }
        }
      }
    }
  `;

  try {
    const response = await admin.graphql(query);
    const result = await response.json();
    const edges = result.data?.customers?.edges || [];

    const generations = await getAiImageGenerations(admin);

    return edges.map(({ node }) => {
      const profile = node.metafield?.value ? parseJson(node.metafield.value) : {};
      
      // Calculate active generation count for this specific customer
      const count = generations.filter(gen => gen.customerId === node.id).length;

      return {
        id: node.id,
        shopifyCustomerId: node.id,
        displayName: node.displayName || node.email || "Shopify Customer",
        email: node.email,
        isApproved: profile.isApproved !== false, // default true
        generationLimit: profile.generationLimit ?? null,
        _count: {
          generations: count
        }
      };
    });
  } catch (err) {
    console.error("getCustomers error", err);
    return [];
  }
}
