import prisma from "../db.server";

export async function getOrCreateShop(shopDomain) {
  return prisma.shop.upsert({
    where: { shop: shopDomain },
    update: {},
    create: {
      shop: shopDomain,
      settings: {
        defaultVisibility: "PRIVATE",
        watermarkText: "Generated by AI",
        moderationEnabled: true,
      },
    },
  });
}

export async function getOrCreateCustomer({ shopId, shopifyCustomerId, email }) {
  if (!shopifyCustomerId && !email) return null;

  const existing = await prisma.customerAccount.findFirst({
    where: {
      shopId,
      OR: [
        shopifyCustomerId ? { shopifyCustomerId } : undefined,
        email ? { email } : undefined,
      ].filter(Boolean),
    },
  });

  if (existing) return existing;

  return prisma.customerAccount.create({
    data: {
      shopId,
      shopifyCustomerId,
      email,
    },
  });
}
