import {
  getShopSettings,
  updateShopSettings,
  getCustomerProfile,
  updateCustomerProfile,
  ensureMetaobjectDefinition
} from "./metaobjects.server";

export async function getOrCreateShop(admin, shopDomain) {
  // Ensure the AI generation metaobject definition is created
  await ensureMetaobjectDefinition(admin);

  let settingsStr = await getShopSettings(admin);
  let settings;

  if (!settingsStr) {
    settings = defaultShopSettings();
    settingsStr = JSON.stringify(settings);
    await updateShopSettings(admin, settingsStr);
  } else {
    settings = parseShopSettings(settingsStr);
  }

  // Map to the object structure expected by the rest of the application
  return {
    id: shopDomain,
    shop: shopDomain,
    settings: JSON.stringify(settings),
  };
}

export function defaultShopSettings() {
  return {
    defaultVisibility: "PRIVATE",
    watermarkText: "Generated by AI",
    moderationEnabled: true,
    studioProduct: {
      title: "Generate your own image",
      checkoutVariantId: "",
      promptInstructions:
        "Create premium print-ready wall art. Respect the selected product options exactly.",
      optionGroups: [
        {
          name: "Size",
          promptLabel: "print size",
          values: ["8 x 10 in", "12 x 16 in", "18 x 24 in"],
        },
        {
          name: "Frame",
          promptLabel: "frame style",
          values: ["No frame", "Black frame", "Walnut frame", "White frame"],
        },
        {
          name: "Fabric",
          promptLabel: "material",
          values: ["Fine art paper", "Canvas", "Textured cotton"],
        },
      ],
      promptTemplates: [
        "minimal gallery wall, premium print art, soft natural light",
        "bold abstract print, textured brushwork, curated interior styling",
        "calm spiritual artwork, refined color palette, elegant framed print",
      ],
    },
  };
}

export function parseShopSettings(settings) {
  let parsed = {};

  try {
    parsed = settings ? JSON.parse(settings) : {};
  } catch {
    parsed = {};
  }

  const defaults = defaultShopSettings();
  return {
    ...defaults,
    ...parsed,
    studioProduct: {
      ...defaults.studioProduct,
      ...(parsed.studioProduct || {}),
      optionGroups: Array.isArray(parsed.studioProduct?.optionGroups)
        ? parsed.studioProduct.optionGroups
        : defaults.studioProduct.optionGroups,
      promptTemplates: Array.isArray(parsed.studioProduct?.promptTemplates)
        ? parsed.studioProduct.promptTemplates
        : defaults.studioProduct.promptTemplates,
    },
  };
}

export async function getOrCreateCustomer({ admin, shopId, shopifyCustomerId, email }) {
  if (!shopifyCustomerId) return null;

  // Fetch the customer's custom approval/limit profile from their Shopify Customer metafields
  let profile = await getCustomerProfile(admin, shopifyCustomerId);

  if (!profile) {
    // If new, initialize their profile with defaults
    profile = await updateCustomerProfile(admin, shopifyCustomerId, {
      isApproved: true,
      generationLimit: null,
      totalGenerations: 0,
    });
  }

  // Map to the object structure expected by the application
  return {
    id: shopifyCustomerId,
    shopId,
    shopifyCustomerId,
    email: email || null,
    displayName: email ? email.split("@")[0] : "Customer",
    isApproved: profile.isApproved !== false,
    generationLimit: profile.generationLimit ?? null,
  };
}
