import { authenticate, unauthenticated } from "../shopify.server";
import { generateAiImage } from "../services/openai-images.server";
import { moderatePrompt } from "../services/moderation.server";
import { getOrCreateCustomer, getOrCreateShop, parseShopSettings } from "../services/shops.server";
import { corsJson, optionsResponse } from "../services/cors.server";
import { isLiveGeneration } from "../services/generation-mode.server";
import {
  createAiImageGeneration,
  updateAiImageGeneration,
  getAiImageGenerations,
  updateCustomerProfile
} from "../services/metaobjects.server";

export async function loader() {
  return optionsResponse();
}

export async function action({ request }) {
  if (request.method === "OPTIONS") return optionsResponse();

  try {
    const body = await request.json();
    const {
      prompt,
      productId,
      productHandle,
      variantId,
      variantTitle,
      selectedOptions,
      originalPrompt,
      customerId,
      customerEmail,
      visibility = "PRIVATE",
      shop: shopFromBody,
    } = body;

    if (!prompt || typeof prompt !== "string" || prompt.trim().length < 3) {
      return corsJson({ success: false, error: "Prompt is required." });
    }

    let shopDomain = shopFromBody;
    let adminClient;

    try {
      const auth = await authenticate.admin(request);
      shopDomain = auth.session.shop;
      adminClient = auth.admin;
    } catch {
      if (shopFromBody) {
        const auth = await unauthenticated.admin(shopFromBody);
        shopDomain = shopFromBody;
        adminClient = auth.admin;
      }
    }

    if (!shopDomain || !adminClient) {
      return corsJson({ success: false, error: "Shop domain and admin authentication are required." });
    }

    const shop = await getOrCreateShop(adminClient, shopDomain);
    const settings = parseShopSettings(shop.settings);
    const customer = await getOrCreateCustomer({
      admin: adminClient,
      shopId: shop.id,
      shopifyCustomerId: customerId,
      email: customerEmail,
    });

    if (customer?.isApproved === false) {
        return corsJson({ success: false, error: "Your account is waiting for approval." });
    }

    const customerLimit = customer?.generationLimit;
    if (customer && Number.isInteger(customerLimit)) {
      const gens = await getAiImageGenerations(adminClient, { customerId: customer.id });
      const used = gens.length;
      if (used >= customerLimit) {
        return corsJson({ success: false, error: "Your image generation limit has been reached." });
      }
    }

    const optionSummary = Array.isArray(selectedOptions)
      ? selectedOptions
          .filter((option) => option?.name && option?.value)
          .map((option) => `${option.name}: ${option.value}`)
          .join(", ")
      : "";
    const studioPrompt = [
      prompt.trim(),
      settings.studioProduct?.promptInstructions,
      optionSummary ? `Selected customization options: ${optionSummary}.` : "",
    ]
      .filter(Boolean)
      .join("\n\n");

    const generation = await createAiImageGeneration(adminClient, {
      prompt: studioPrompt,
      status: "PROCESSING",
      visibility: visibility === "PUBLIC" ? "PUBLIC" : "PRIVATE",
      moderationStatus: "PENDING",
      productId,
      productHandle,
      variantId,
      variantTitle,
      customerId: customer?.id,
      customerEmail,
    });

    if (isLiveGeneration()) {
      const moderation = await moderatePrompt(studioPrompt);
      if (!moderation.allowed) {
        const blocked = await updateAiImageGeneration(adminClient, generation.id, {
          status: "BLOCKED",
          moderationStatus: "REJECTED",
          moderationReason: moderation.reason,
        });

        return corsJson({ success: false, error: moderation.reason, generation: blocked });
      }
    }

    const image = await generateAiImage(
      `${studioPrompt}\n\nInclude a tasteful visible watermark text: "${settings.watermarkText || "Generated by AI"}".`,
    );

    const saved = await updateAiImageGeneration(adminClient, generation.id, {
      imageUrl: image.imageUrl,
      status: "COMPLETED",
      moderationStatus: visibility === "PUBLIC" ? "PENDING" : "APPROVED",
      openAiRequestId: image.requestId,
      metadata: JSON.stringify({
        productHandle,
        variantId,
        variantTitle,
        selectedOptions,
        originalPrompt: originalPrompt || prompt.trim(),
        generationMode: image.mode,
      }),
    });

    // Increment Customer's total generation count in their profile metafield
    if (customer?.id) {
      const profile = await getOrCreateCustomer({
        admin: adminClient,
        shopId: shop.id,
        shopifyCustomerId: customer.id,
        email: customerEmail,
      });
      await updateCustomerProfile(adminClient, customer.id, {
        totalGenerations: (profile.totalGenerations || 0) + 1
      });
    }

    console.log("OpenAI Usage Log (Local Node Server logs):", {
      model: image.model,
      imageCount: 1,
      requestId: image.requestId,
      status: "COMPLETED",
    });

    return corsJson({
      success: true,
      generation: saved,
      image: saved.imageUrl,
      mode: image.mode,
    });
  } catch (error) {
    console.error("Image generation failed", error);
    return corsJson({
      success: false,
      error: error.message,
    });
  }
}
