import { authenticate, unauthenticated } from "../shopify.server";
import { generateAiImage } from "../services/openai-images.server";
import { moderatePrompt } from "../services/moderation.server";
import {
  defaultShopSettings,
  getOrCreateCustomer,
  getOrCreateShop,
  parseShopSettings,
} from "../services/shops.server";
import { corsJson, optionsResponse } from "../services/cors.server";
import { isLiveGeneration } from "../services/generation-mode.server";
import { getAiImageGenerations } from "../services/metaobjects.server";
import { saveGeneratedImageToPublicUrl } from "../services/shopify-media.server";

export async function loader() {
  return optionsResponse();
}

export async function action({ request }) {
  if (request.method === "OPTIONS") return optionsResponse();

  try {
    const body = await request.json();
    const {
      prompt,
      productId,
      productHandle,
      variantId,
      variantTitle,
      selectedOptions,
      originalPrompt,
      customerId,
      customerEmail,
      visibility = "PRIVATE",
      apiBase,
      shop: shopFromBody,
    } = body;

    if (!prompt || typeof prompt !== "string" || prompt.trim().length < 3) {
      return corsJson({ success: false, error: "Prompt is required." });
    }
    if (prompt.length > 4000 || /data:image\/|;base64,/i.test(prompt)) {
      return corsJson({
        success: false,
        error: "Prompt is too large. Please enter text only.",
      });
    }

    let shopDomain = shopFromBody;
    let adminClient;

    try {
      const auth = await authenticate.admin(request);
      shopDomain = auth.session.shop;
      adminClient = auth.admin;
    } catch {
      if (shopFromBody) {
        try {
          const auth = await unauthenticated.admin(shopFromBody);
          shopDomain = shopFromBody;
          adminClient = auth.admin;
        } catch (error) {
          if (!isMissingShopifySessionError(error)) {
            throw error;
          }
          shopDomain = shopFromBody;
          adminClient = null;
        }
      }
    }

    if (!shopDomain) {
      return corsJson({
        success: false,
        error: "Shop domain is required.",
      });
    }

    const shop = adminClient
      ? await getOrCreateShop(adminClient, shopDomain)
      : {
          id: shopDomain,
          shop: shopDomain,
          settings: JSON.stringify(defaultShopSettings()),
        };
    const settings = parseShopSettings(shop.settings);
    const customer = adminClient
      ? await getOrCreateCustomer({
          admin: adminClient,
          shopId: shop.id,
          shopifyCustomerId: customerId,
          email: customerEmail,
        })
      : customerId
        ? {
            id: customerId,
            shopId: shop.id,
            shopifyCustomerId: customerId,
            email: customerEmail || null,
            displayName: customerEmail
              ? customerEmail.split("@")[0]
              : "Customer",
            isApproved: true,
            generationLimit: null,
          }
        : null;

    if (customer?.isApproved === false) {
      return corsJson({
        success: false,
        error: "Your account is waiting for approval.",
      });
    }

    const customerLimit = customer?.generationLimit;
    if (customer && Number.isInteger(customerLimit)) {
      const gens = await getAiImageGenerations(adminClient, {
        shopId: shop.id,
        customerId: customer.id,
      });
      const used = gens.length;
      if (used >= customerLimit) {
        return corsJson({
          success: false,
          error: "Your image generation limit has been reached.",
        });
      }
    }

    const optionSummary = Array.isArray(selectedOptions)
      ? selectedOptions
          .filter((option) => option?.name && option?.value)
          .map((option) => `${option.name}: ${option.value}`)
          .join(", ")
      : "";
    const studioPrompt = [
      prompt.trim(),
      settings.studioProduct?.promptInstructions,
      optionSummary ? `Selected customization options: ${optionSummary}.` : "",
    ]
      .filter(Boolean)
      .join("\n\n");

    if (isLiveGeneration()) {
      const moderation = await moderatePrompt(studioPrompt);
      if (!moderation.allowed) {
        return corsJson({
          success: false,
          error: moderation.reason,
        });
      }
    }

    const image = await generateAiImage(
      `${studioPrompt}\n\nInclude a tasteful visible watermark text: "${settings.watermarkText || "Generated by AI"}".`,
    );

    const publicBaseUrl =
      process.env.APP_PUBLIC_URL ||
      process.env.SHOPIFY_APP_URL ||
      process.env.HOST ||
      "https://shopify-ai.deploymeta.com";
    const previewImage = await saveGeneratedImageToPublicUrl({
      imageUrl: image.imageUrl,
      base64Data: image.base64Data,
      mimeType: image.mimeType,
      publicBaseUrl,
    });

    if (!previewImage || previewImage.startsWith("data:")) {
      throw new Error(
        "Generated image could not be converted to a preview image URL.",
      );
    }
    const storefrontPreviewImage = storefrontImageUrl(previewImage, apiBase);

    const pendingGeneration = {
      prompt: studioPrompt,
      status: "PREVIEW",
      visibility: visibility === "PUBLIC" ? "PUBLIC" : "PRIVATE",
      moderationStatus: visibility === "PUBLIC" ? "PENDING" : "APPROVED",
      productId,
      productHandle,
      variantId,
      variantTitle,
      customerId: customer?.id || customerId || null,
      customerEmail,
      imageUrl: storefrontPreviewImage,
      openAiRequestId: image.requestId,
      metadata: JSON.stringify({
        productHandle,
        variantId,
        variantTitle,
        selectedOptions,
        originalPrompt: originalPrompt || prompt.trim(),
        generationMode: image.mode,
      }),
      pendingImage: {
        imageUrl: storefrontPreviewImage,
        mimeType: image.mimeType,
      },
    };

    console.log("OpenAI Usage Log (Local Node Server logs):", {
      model: image.model,
      imageCount: 1,
      requestId: image.requestId,
      status: "COMPLETED",
    });

    return corsJson({
      success: true,
      generation: pendingGeneration,
      image: storefrontPreviewImage,
      mode: image.mode,
    });
  } catch (error) {
    console.error("Image generation failed", error);
    try {
      const fs = await import("fs");
      fs.writeFileSync(
        "./error_debug.log",
        `${new Date().toISOString()}\nError: ${error.message}\nStack: ${error.stack}\n`,
      );
    } catch (e) {
      console.error("Failed to write debug log", e);
    }
    return corsJson({
      success: false,
      error: error.message,
    });
  }
}

function isMissingShopifySessionError(error) {
  return String(error?.message || error).includes("Could not find a session");
}

function storefrontImageUrl(imageUrl, apiBase) {
  const filename = String(imageUrl || "").match(
    /\/ai-generated\/([^/?#]+\.(?:png|jpe?g))/i,
  )?.[1];
  if (!filename) return imageUrl;

  const base = String(apiBase || "/apps/ai-image")
    .trim()
    .replace(/\/$/, "");
  if (!base || /^https?:\/\/localhost(?::|\/|$)/i.test(base)) {
    return `/apps/ai-image/ai-generated/${filename}`;
  }

  if (/^https?:\/\//i.test(base)) {
    const url = new URL(base);
    const pathname = url.pathname.replace(/\/api\/?$/i, "");
    return `${url.origin}${pathname}/ai-generated/${filename}`;
  }

  return `${base}/ai-generated/${filename}`;
}
