import prisma from "../db.server";
import { authenticate, unauthenticated } from "../shopify.server";
import { generateAiImage } from "../services/openai-images.server";
import { moderatePrompt } from "../services/moderation.server";
import { getOrCreateCustomer, getOrCreateShop, parseShopSettings } from "../services/shops.server";
import { corsJson, optionsResponse } from "../services/cors.server";
import { isLiveGeneration } from "../services/generation-mode.server";

export async function loader() {
  return optionsResponse();
}

export async function action({ request }) {
  if (request.method === "OPTIONS") return optionsResponse();

  try {
    const body = await request.json();
    const {
      prompt,
      productId,
      productHandle,
      variantId,
      variantTitle,
      selectedOptions,
      originalPrompt,
      customerId,
      customerEmail,
      visibility = "PRIVATE",
      shop: shopFromBody,
    } = body;

    if (!prompt || typeof prompt !== "string" || prompt.trim().length < 3) {
      return corsJson({ success: false, error: "Prompt is required." }, { status: 400 });
    }

    let shopDomain = shopFromBody;

    try {
      const auth = await authenticate.admin(request);
      shopDomain = auth.session.shop;
    } catch {
      if (shopFromBody) {
        await unauthenticated.admin(shopFromBody);
        shopDomain = shopFromBody;
      }
    }

    if (!shopDomain) {
      return corsJson(
        { success: false, error: "Shop domain is required." },
        { status: 401 },
      );
    }

    const shop = await getOrCreateShop(shopDomain);
    const settings = parseShopSettings(shop.settings);
    const customer = await getOrCreateCustomer({
      shopId: shop.id,
      shopifyCustomerId: customerId,
      email: customerEmail,
    });

    if (customer?.isApproved === false) {
        return corsJson(
          { success: false, error: "Your account is waiting for approval." },
          { status: 403 },
        );
    }

    const customerLimit = customer?.generationLimit;
    if (customer && Number.isInteger(customerLimit)) {
      const used = await prisma.aiImageGeneration.count({
        where: { shopId: shop.id, customerId: customer.id },
      });
      if (used >= customerLimit) {
        return corsJson(
          { success: false, error: "Your image generation limit has been reached." },
          { status: 403 },
        );
      }
    }

    const optionSummary = Array.isArray(selectedOptions)
      ? selectedOptions
          .filter((option) => option?.name && option?.value)
          .map((option) => `${option.name}: ${option.value}`)
          .join(", ")
      : "";
    const studioPrompt = [
      prompt.trim(),
      settings.studioProduct?.promptInstructions,
      optionSummary ? `Selected customization options: ${optionSummary}.` : "",
    ]
      .filter(Boolean)
      .join("\n\n");
    const db = prisma;
    const generation = await db.aiImageGeneration.create({
      data: {
        shopId: shop.id,
        customerId: customer?.id,
        productId,
        productHandle,
        variantId,
        variantTitle,
        prompt: studioPrompt,
        visibility: visibility === "PUBLIC" ? "PUBLIC" : "PRIVATE",
        status: "PROCESSING",
        moderationStatus: "PENDING",
      },
    });

    if (isLiveGeneration()) {
      const moderation = await moderatePrompt(studioPrompt);
      if (!moderation.allowed) {
        const blocked = await db.aiImageGeneration.update({
          where: { id: generation.id },
          data: {
            status: "BLOCKED",
            moderationStatus: "REJECTED",
            moderationReason: moderation.reason,
          },
        });

        return corsJson(
          { success: false, error: moderation.reason, generation: blocked },
          { status: 422 },
        );
      }
    }

    const image = await generateAiImage(
      `${studioPrompt}\n\nInclude a tasteful visible watermark text: "${settings.watermarkText || "Generated by AI"}".`,
    );

    const saved = await db.aiImageGeneration.update({
      where: { id: generation.id },
      data: {
        imageUrl: image.imageUrl,
        status: "COMPLETED",
        moderationStatus: visibility === "PUBLIC" ? "PENDING" : "APPROVED",
        openAiRequestId: image.requestId,
        metadata: JSON.stringify({
          productHandle,
          variantId,
          variantTitle,
          selectedOptions,
          originalPrompt: originalPrompt || prompt.trim(),
          generationMode: image.mode,
        }),
      },
    });

    await db.openAiUsageLog.create({
      data: {
        shopId: shop.id,
      generationId: saved.id,
      model: image.model,
        imageCount: 1,
        requestId: image.requestId,
      status: "COMPLETED",
    },
  });

    return corsJson({
      success: true,
      generation: saved,
      image: saved.imageUrl,
      mode: image.mode,
    });
  } catch (error) {
    console.error("Image generation failed", error);
    return corsJson({
      success: false,
      error: error.message,
    }, { status: 500 });
  }
}
